[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "dist"
  environment = { NODE_VERSION = "20.0.0" }

[context.production.environment]
  VITE_APP_VERSION = "2.0.0"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/moroccan-bac-calculator.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/png"

[[redirects]]
  from = "/favicon.ico"
  to = "/moroccan-bac-calculator.png"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200